version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3001:3001"      
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.0
    volumes:
      - ${DOCKER_MONGO_DATA_DIR}:/data/db
    ports:
      - "27017:27017"
