version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.0
    volumes:
      - ${DOCKER_MONGO_DATA_DIR}:/data/db
    ports:
      - "27017:27017"
